[package]
name = "merlin"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11.5"
tokio = { version = "1.41.1", features = ["rt-multi-thread", "macros"] }
wgpu = "23.0.1"
winit = "0.30.5"
